use pizza_dashboard;
select * from pizza_sales;

-- Step 1: convert text type to date type
ALTER TABLE pizza_sales ADD COLUMN order_dates DATE;
UPDATE pizza_sales 
SET order_dates = STR_TO_DATE(order_date, '%d-%m-%Y');
ALTER TABLE pizza_sales DROP COLUMN order_date;
--  Rename the new DATE column to the original column name
ALTER TABLE pizza_sales RENAME COLUMN order_dates TO order_date;

-- Step 2: Convert the text data to time type
ALTER TABLE pizza_sales ADD COLUMN order_times time;
UPDATE pizza_sales 
SET order_times = STR_TO_DATE(order_time, '%H:%i:%s');
ALTER TABLE pizza_sales DROP COLUMN order_time;
--  Rename the new DATE column to the original column name
ALTER TABLE pizza_sales RENAME COLUMN order_times TO order_time;

# What is the Total Revenue generated by all the pizza orders?
select sum(total_price) as 'TOTAL REVENUE' from pizza_sales;

# What is the Average Order Value?
select sum(total_price)/count(distinct order_id) as 'Average Order Value' from pizza_sales;

#Total Pizza sold:
select sum(quantity) as 'Total Pizza Sold' from pizza_sales;

#Total Orders:
select count(distinct order_id) as 'Total Orders' from pizza_sales;

#Average Pizzas per order:
select sum(quantity)/count(distinct order_id) as 'Average Pizzas per order' from pizza_sales;

#daily trnds of sales:
SELECT 
    DATE_FORMAT(order_date, '%W'), COUNT(DISTINCT order_id)
FROM
    pizza_sales
GROUP BY DATE_FORMAT(order_date, '%W');

#Monthly trnds of sales :
select date_format(order_date, '%M'), COUNT(DISTINCT order_id)
FROM
    pizza_sales
GROUP BY  date_format(order_date, '%M');

#Percentage of sales by pizza category :
select * from pizza_sales;
select pizza_category,sum(total_price)*100/(select sum(total_price) from pizza_sales) as 'Percentage of sales by pizza category'
from pizza_sales group by pizza_category;

#Total pizza sold by pizza category:
select pizza_size,cast(sum(total_price) as decimal(10,2)) as 'Total Revenue' ,
cast(sum(total_price)*100/(select sum(total_price) from pizza_sales where quarter(order_date)=1) as decimal(10,2)) as 'PCT' from pizza_sales
where quarter(order_date)=1
group by pizza_size
order by PCT desc;

#Top 5 Bestsellers by Total sales,total Quantity and Total Order :
select pizza_name , sum(total_price) as 'Total Revenue'
from  pizza_sales group by pizza_name
order by sum(total_price) desc limit 5;

select pizza_name , sum(quantity) as 'Total Quantity'
from  pizza_sales group by pizza_name
order by sum(quantity) desc limit 5;

select pizza_name , count(distinct order_id) as 'Total Orders'
from  pizza_sales group by pizza_name
order by count(distinct order_id) desc limit 5;

# Bottom 5 Bestsellers by Total sales,total Quantity and Total Order :
select pizza_name , sum(total_price) as 'Total Revenue'
from  pizza_sales group by pizza_name
order by sum(total_price) asc limit 5;

select pizza_name , sum(quantity) as 'Total Quantity'
from  pizza_sales group by pizza_name
order by sum(quantity) asc limit 5;

select pizza_name , count(distinct order_id) as 'Total Orders'
from  pizza_sales group by pizza_name
order by count(distinct order_id) asc limit 5;